#!/usr/bin/env node
/**
 * Create mobile/.env from root .env.local (maps NEXT_PUBLIC_* → EXPO_PUBLIC_*).
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const mobileRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(mobileRoot, '..');
const sourcePath = path.join(repoRoot, '.env.local');
const targetPath = path.join(mobileRoot, '.env');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const env = {};
  for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

const rootEnv = parseEnvFile(sourcePath);
const existing = parseEnvFile(targetPath);

const apiUrl =
  existing.EXPO_PUBLIC_API_URL ||
  rootEnv.EXPO_PUBLIC_API_URL ||
  rootEnv.NEXT_PUBLIC_APP_URL ||
  'http://10.0.2.2:3000';

const supabaseUrl =
  existing.EXPO_PUBLIC_SUPABASE_URL ||
  rootEnv.EXPO_PUBLIC_SUPABASE_URL ||
  rootEnv.NEXT_PUBLIC_SUPABASE_URL ||
  '';

const supabaseKey =
  existing.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  rootEnv.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  rootEnv.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  '';

const lines = [
  '# Generated by mobile/scripts/sync-env.mjs — edit as needed',
  `EXPO_PUBLIC_API_URL=${apiUrl}`,
];

if (supabaseUrl) {
  lines.push(`EXPO_PUBLIC_SUPABASE_URL=${supabaseUrl}`);
}
if (supabaseKey) {
  lines.push(`EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${supabaseKey}`);
}

fs.writeFileSync(targetPath, `${lines.join('\n')}\n`, 'utf8');
console.log(`Wrote ${targetPath}`);
if (!fs.existsSync(sourcePath)) {
  console.log('Note: root .env.local not found — using defaults for API URL only.');
}
